export default {
  code:"sv",lang:"sv",suffix:".sv",
  text:{
    localeCode:"sv",
    appTitle:"SQL och relationsdatabaser",
    brandSubtitle:"Öva exakt mental exekvering av frågor, NULL-logik, joinar, grupper, transaktioner, normalisering och index i små syntetiska tabeller.",
    educationalNote:"Fast modell: PracticeSQL-1 · endast syntetiska lokala data · ingen databasanslutning, serverdel eller körning mot verkliga system.",
    summary:{aria:"Sammanfattning av framsteg",mastery:"Snittnivå",accuracy:"Träffsäkerhet",attempts:"Försök"},
    nav:{aria:"Huvudmeny",practice:"Öva",matrix:"Matris",stats:"Statistik",settings:"Inställningar",learn:"Lär dig"},
    practice:{modeAria:"Övningsläge",adaptive:"Adaptivt",manual:"Manuellt",pause:"Pausa",paused:"Pausad",learnThis:"Lär dig detta",category:"Kategori",family:"Frågefamilj",level:"Nivå",mastery:"0 % behärskning",masterySuffix:"behärskning",check:"Kontrollera",next:"Nästa",skip:"Hoppa över",choose:"Välj…",keypadAria:"Strukturerad svarsknappsats",delete:"Radera",clear:"Rensa",nextField:"Flytta till nästa svarsfält",nextFieldShort:"Fält →",pauseText:"Tidtagningen är stoppad för den här frågan.",resume:"Fortsätt",controlsAria:"Övningskontroller",masteryMetric:"Behärskning",accuracyMetric:"Träffsäkerhet",streak:"Svit",avgTime:"Snittid"},
    matrix:{title:"Färdighetsmatris",intro:"Varje cell öppnar en stabil familj inom SQL eller relationsresonemang på en strukturell svårighetsnivå."},
    stats:{title:"Statistik",intro:"Framsteg följs separat för varje familj och nivå.",totalAttempts:"Totalt antal försök",totalCorrect:"Rätt svar",totalTime:"Total tid",practicedLevels:"Övade nivåer",needsWork:"Behöver övas",strongest:"Starkast",tries:"försök",noAttemptsYet:"Inga försök ännu"},
    settings:{title:"Inställningar",intro:"Lagras lokalt i den här webbläsaren.",adaptiveCategories:"Kategorier i adaptivt läge",data:"Data",dataIntro:"Exportera, importera eller återställ lokala framsteg.",progressJson:"Framsteg som JSON",export:"Exportera",copy:"Kopiera",import:"Importera",reset:"Återställ"},
    learn:{title:"Lär dig",intro:"Regler för PracticeSQL-1, representativa exempel och den viktiga fallgropen för varje familj.",familyConcept:"Öva {family} enligt den exakta modellen PracticeSQL-1."},
    messages:{correct:"Rätt",notQuite:"Inte riktigt",expected:"Förväntat",time:"Tid",invalidJson:"Ogiltig JSON",imported:"Framstegen importerades.",copied:"Framstegen kopierades.",resetConfirm:"Återställa alla lokala SQL-framsteg?"},
    fieldLabels:{answer:"Svar",count:"Antal",result:"Resultat",rows:"Rader",value:"Värde",cost:"Kostnad",closure:"Slutning"},
    categories:{
      relations:"Relationer, scheman och nycklar","select-filter":"SELECT och filtrering","null-logic":"NULL och trevärd logik","order-duplicates":"Dubbletter, sortering och sidindelning",joins:"Joinar och multiplicitet",aggregation:"Aggregering och gruppering","subqueries-sets":"Underfrågor och mängdoperationer",mutations:"Dataändringar och transaktioner",design:"Relationsdesign och normalisering",indexes:"Index och frågeplanering"
    },
    families:{
      schema_row_column_read:"Läs scheman, rader och kolumner",candidate_superkey:"Kandidatnycklar och supernycklar",primary_foreign_key_map:"Koppla primär- och främmande nycklar",key_constraint_validity:"Kontrollera nyckelvillkor",bag_set_order_distinction:"Skilj på påsar, mängder och ordning",relational_operation_recognition:"Känn igen relationsoperationer",relationship_junction_table:"Utforma kopplingstabeller",
      select_projection:"Exekvera projektionsuttryck",where_comparison_filter:"Filtrera med jämförelser",boolean_precedence:"Tillämpa boolesk prioritet",between_in_filter:"Filtrera med BETWEEN och IN",like_filter:"Matcha med LIKE",case_coalesce_expression:"Beräkna CASE och COALESCE",alias_scope_error:"Slå upp alias och namn",write_single_table_filter:"Konstruera filter för en tabell",
      null_comparison:"Jämför NULL-värden",three_valued_boolean:"Beräkna trevärd logik",where_unknown_filter:"Filtrera UNKNOWN-predikat",is_null_predicate:"Testa saknade värden",null_arithmetic_case:"Följ NULL genom uttryck",null_in_not_in:"Resonera om IN-listor med NULL",unknown_contexts:"Jämför kontexter för UNKNOWN",repair_null_bug:"Reparera NULL-fel",
      projection_multiplicity:"Följ projektionens multiplicitet",distinct_result:"Exekvera DISTINCT",order_by_single_multi:"Sortera på en eller flera nycklar",null_ordering_explicit:"Placera NULL uttryckligen",sort_tie_determinism:"Upptäck lika sorteringsnycklar",limit_offset:"Tillämpa LIMIT och OFFSET",
      cross_join_result:"Exekvera CROSS JOIN",inner_join_result:"Exekvera INNER JOIN",join_null_keys:"Joina nycklar med NULL",left_join_result:"Exekvera LEFT JOIN",on_vs_where_outer_join:"Skilj ON från WHERE",self_join:"Resonera om självjoinar",many_to_many_join:"Följ många-till-många-joinar",join_cardinality_bounds:"Beräkna joinens kardinalitet",write_join_query:"Konstruera joinfrågor",
      aggregate_single_group:"Beräkna aggregat över en grupp",count_star_expression_distinct:"Jämför former av COUNT",group_by_result:"Exekvera GROUP BY",where_before_group:"Filtrera före gruppering",having_group_filter:"Filtrera grupper med HAVING",grouping_validity:"Validera grupperad projektion",outer_join_zero_count:"Räkna föräldrar utan barn",write_aggregate_query:"Konstruera aggregatfrågor",
      scalar_subquery:"Beräkna skalära underfrågor",exists_subquery:"Beräkna EXISTS",correlated_exists:"Följ korrelerad EXISTS",in_subquery:"Beräkna IN-underfrågor",any_all_quantifier:"Beräkna ANY och ALL",union_all_union:"Jämför UNION och UNION ALL",intersect_except:"Exekvera INTERSECT och EXCEPT",set_operation_validity:"Validera mängdoperationer",
      insert_defaults_constraints:"Följ INSERT och standardvärden",update_result:"Följ UPDATE",delete_result:"Följ DELETE",check_not_null_unique:"Beräkna deklarativa villkor",foreign_key_action:"Tillämpa främmande-nyckelåtgärder",statement_atomicity:"Tillämpa satsatomicitet",transaction_commit_rollback:"Följ COMMIT och ROLLBACK",isolation_schedule:"Följ förenklade isoleringsscheman",
      functional_dependency_check:"Kontrollera funktionella beroenden",attribute_closure:"Beräkna attributslutning",anomaly_identification:"Identifiera dataanomalier",normal_form_classify:"Klassificera normalformer",decompose_schema:"Dekomponera scheman",lossless_join_check:"Kontrollera förlustfri dekomposition",schema_relationship_design:"Utforma relationsscheman",
      btree_prefix_usability:"Använd B-trädsprefix",index_lookup_trace:"Följ indexuppslag",covering_index:"Känn igen täckande index",selectivity_plan_choice:"Välj plan från givna kostnader",index_write_tradeoff:"Balansera läsningar och skrivningar för index",plan_semantics_distinction:"Skilj planer från semantik"
    },
    familyRules:{
      schema_row_column_read:"Ett schema deklarerar kolumner, typer och villkor; aktuella rader skapar inte odeklarerade villkor.",candidate_superkey:"En supernyckel bestämmer varje attribut; en kandidatnyckel är en minimal supernyckel.",primary_foreign_key_map:"En främmande nyckel finns på det refererande barnet; unikhet och nullbarhet bestämmer kardinalitet och valfrihet.",key_constraint_validity:"Primärnycklar är unika och inte NULL; nullbar UNIQUE tillåter flera NULL; en icke-null främmande nyckel måste hitta en förälder.",bag_set_order_distinction:"Frågeresultat är oordnade påsar som standard. DISTINCT och mängdoperationer tar bort dubbletter; ORDER BY skapar ordning.",relational_operation_recognition:"WHERE väljer rader, urvalslistan projicerar kolumner, JOIN bildar par, GROUP BY grupperar och DISTINCT tar bort dubbletter.",relationship_junction_table:"En många-till-många-relation använder en kopplingstabell med främmande nycklar till båda föräldrarna och normalt ett unikt par.",
      select_projection:"FROM ger rader; urvalslistan beräknar uttryck per rad och bevarar multiplicitet.",where_comparison_filter:"WHERE beräknar sitt predikat per rad och behåller endast TRUE.",boolean_precedence:"NOT binder före AND, och AND binder före OR; parenteser åsidosätter ordningen.",between_in_filter:"BETWEEN är inklusivt; IN är en disjunktion av likhetsjämförelser.",like_filter:"LIKE matchar hela strängen; % täcker valfritt antal kodpunkter och _ exakt en; matchningen är skiftlägeskänslig.",case_coalesce_expression:"CASE använder den första TRUE-grenen; COALESCE returnerar det första argumentet som inte är NULL.",alias_scope_error:"Ett urvalsalias är synligt endast för ORDER BY; okvalificerade namn i joinar måste vara entydiga.",write_single_table_filter:"Välj projektion och predikat efter semantik, inklusive inklusiva gränser och uttryckliga parenteser.",
      null_comparison:"Varje vanlig jämförelse med NULL är UNKNOWN; IS [NOT] DISTINCT FROM är NULL-säker.",three_valued_boolean:"SQL:s booleska värden är TRUE, FALSE och UNKNOWN; NOT UNKNOWN förblir UNKNOWN.",where_unknown_filter:"WHERE behåller endast TRUE; både FALSE och UNKNOWN tas bort.",is_null_predicate:"IS NULL och IS NOT NULL ger vanliga booleska resultat; NULL skiljer sig från tom text, noll och 'NULL'.",null_arithmetic_case:"Vanlig aritmetik och konkatenering sprider NULL; CASE väljer en gren endast vid TRUE.",null_in_not_in:"IN är ett OR av jämförelser; ingen träff plus ett NULL ger UNKNOWN, och NOT bevarar UNKNOWN.",unknown_contexts:"WHERE, ON, HAVING och CASE avvisar UNKNOWN; CHECK godtar det eftersom endast FALSE underkänns.",repair_null_bug:"Använd IS NULL, NULL-säkra jämförelser eller korrelerad NOT EXISTS enligt den avsedda semantiken.",
      projection_multiplicity:"Projektion avger ett resultat per indatarad även när värden blir lika.",distinct_result:"DISTINCT slår samman fullständiga rader som inte är distinkta; upprepade NULL slås samman.",order_by_single_multi:"ORDER BY jämför nycklar från vänster till höger; varje nyckel har egen riktning.",null_ordering_explicit:"NULLS FIRST eller LAST är oberoende av ASC eller DESC för värden som inte är NULL.",sort_tie_determinism:"Olika resultatrader med samma värden för alla sorteringsnycklar är oordnade jämlikar utan utslagsnyckel.",limit_offset:"Sortering sker först, OFFSET kastar rader och LIMIT tar sedan rader.",
      cross_join_result:"CROSS JOIN avger varje ordnat par; radantal multipliceras.",inner_join_result:"En innerjoin avger varje par vars ON-predikat är TRUE; upprepade nycklar multiplicerar träffar.",join_null_keys:"NULL=NULL med vanlig likhet är UNKNOWN och därför ingen jointräff.",left_join_result:"En vänsterjoin avger alla TRUE-träffar, eller exakt en rad med NULL på högersidan när inga träffar finns.",on_vs_where_outer_join:"ON bestämmer träffar före utfyllnad; WHERE filtrerar de joinade och utfyllda raderna efteråt.",self_join:"Alias är oberoende instanser av samma tabell och måste användas för att relatera rader.",many_to_many_join:"Joina varje förälder genom kopplingstabellen; multipliciteten följer kopplingsraderna.",join_cardinality_bounds:"För en inre likhetsjoin summeras countA(k)×countB(k) över nycklar som inte är NULL.",write_join_query:"Välj rätt jointyp, riktning, nyckel och predikatfas för kravet.",
      aggregate_single_group:"COUNT(*) räknar rader; andra aggregat ignorerar NULL, och en aggregatfråga utan GROUP BY bildar en grupp.",count_star_expression_distinct:"COUNT(*) räknar rader, COUNT(x) räknar x som inte är NULL och COUNT(DISTINCT x) räknar distinkta x som inte är NULL.",group_by_result:"GROUP BY delar upp efter nycklar som inte är distinkta och avger en aggregatrad per överlevande grupp.",where_before_group:"WHERE tar bort indatarader innan grupper och aggregat finns.",having_group_filter:"HAVING beräknas efter aggregat och behåller endast grupper där predikatet är TRUE.",grouping_validity:"Varje valt icke-aggregatuttryck måste finnas i GROUP BY enligt den strikta v1-regeln.",outer_join_zero_count:"Efter LEFT JOIN ska en icke-null barnnyckel räknas, inte COUNT(*), för att utfyllda rader ska ge noll.",write_aggregate_query:"Välj gruppering, fasen WHERE eller HAVING och rätt COUNT-form från det exakta sammanfattningskravet.",
      scalar_subquery:"Noll rader ger NULL, en rad ger dess cell och fler än en rad ger ett kardinalitetsfel.",exists_subquery:"EXISTS är TRUE exakt när underfrågan har minst en rad; projicerade NULL-värden saknar betydelse.",correlated_exists:"En korrelerad underfråga slår upp yttre referenser separat för varje yttre rad.",in_subquery:"IN jämför med underfrågans enkolumnsresultat enligt samma nullbara trevärda regler som en IN-lista.",any_all_quantifier:"ANY är ett OR och ALL ett AND över jämförelser; ANY(tom)=FALSE och ALL(tom)=TRUE.",union_all_union:"UNION ALL bevarar multiplicitet; UNION tillämpar dubblettborttagning som för en mängd.",intersect_except:"Båda använder mängdsemantik och behandlar NULL som inte distinkta vid medlemskap.",set_operation_validity:"Grenarna måste ha samma kolumnantal och kompatibla typer positionsvis; namnen kommer från första grenen.",
      insert_defaults_constraints:"INSERT kopplar namngivna värden, fyller standardvärden och nullbara NULL och kontrollerar sedan hela den nya raden.",update_result:"UPDATE ändrar varje TRUE-rad; alla högerled läser den gamla raden enligt v1:s samtidiga tilldelning.",delete_result:"DELETE tar bort varje TRUE-mål och tillämpar den uttryckliga främmande-nyckelåtgärden atomärt.",check_not_null_unique:"NOT NULL avvisar frånvaro; CHECK avvisar endast FALSE; nullbar UNIQUE tillåter flera NULL.",foreign_key_action:"En icke-null främmande nyckel måste lösas; RESTRICT, CASCADE och SET NULL ger sina deklarerade övergångar.",statement_atomicity:"En sats som lämnar någon berörd rad ogiltig ändrar inga rader alls.",transaction_commit_rollback:"En transaktion läser sina egna skrivningar; COMMIT publicerar dem och ROLLBACK förkastar dem.",isolation_schedule:"Read committed ser senare bekräftade tillstånd per sats; snapshot_v1 behåller ögonblicksbilden från första läsningen och avbryter senare kolliderande skrivare.",
      functional_dependency_check:"X→Y gäller i en instans när rader som är lika på X också är lika på Y; ett urval kan inte bevisa en schemaregel.",attribute_closure:"Lägg upprepade gånger till högerled vars vänsterled redan finns i slutningen tills inget ändras.",anomaly_identification:"Upprepade fakta ger uppdateringsanomalier, oskiljbar skapelse av entiteter ger insättningsanomalier och borttagning av sista raden kan förlora fakta.",normal_form_classify:"2NF tar bort partiella icke-prima beroenden, 3NF tar bort olämpliga transitiva icke-prima beroenden och BCNF kräver att varje determinant är en supernyckel.",decompose_schema:"För X→Y håller en kontrollerad binär dekomposition X∪Y samman och resterande attribut tillsammans med X.",lossless_join_check:"En binär dekomposition är förlustfri när de gemensamma attributen bestämmer hela ena komponenten.",schema_relationship_design:"Placera en främmande nyckel på många-sidan, använd en kopplingstabell för många-till-många och uttryck valfri ett-till-ett med unikhet och nullbarhet.",
      btree_prefix_usability:"En sökning i ett sammansatt B-träd börjar med dess ledande kolumner; det första intervallet stoppar senare avgränsning med söknycklar i v1.",index_lookup_trace:"Börja vid det ordnade nyckelintervallet, skanna dess poster, tillämpa restfilter och hämta rader om indexet inte täcker.",covering_index:"Varje predikat-, rest- och vald kolumn som frågan behöver måste finnas i den visade indexposten.",selectivity_plan_choice:"Beräkna de visade exakta leksakskostnaderna; anta aldrig att ett index automatiskt är billigare.",index_write_tradeoff:"Jämför angiven läsbesparing med underhåll per skrivning och känn igen överflödiga index med samma ledande prefix.",plan_semantics_distinction:"En korrekt plan ändrar hur rader hittas, inte frågeresultatet; utdataordning kräver fortfarande ORDER BY."
    },
    familyExamples:{
      schema_row_column_read:"users(id INTEGER, name TEXT): name har typen TEXT.",candidate_superkey:"A→B och B→C gör {A} till kandidatnyckel för (A,B,C), medan {A,B} inte är minimal.",primary_foreign_key_map:"orders.customer_id → customers.id tillåter många beställningar per kund.",key_constraint_validity:"Ett duplicerat primärnyckelvärde avvisar hela insättningen.",bag_set_order_distinction:"SELECT city kan upprepa städer och lovar ingen ordning.",relational_operation_recognition:"WHERE active=TRUE är logiskt radurval.",relationship_junction_table:"enrollment(student_id, course_id, grade) lagrar relationen student–kurs.",
      select_projection:"SELECT price*2 beräknar en utdata för varje indatarad.",where_comparison_filter:"WHERE age>=18 behåller gränsvärdet 18.",boolean_precedence:"TRUE OR FALSE AND FALSE är TRUE.",between_in_filter:"x BETWEEN 1 AND 2 behåller både 1 och 2.",like_filter:"'Ada%' matchar Ada och Adam, men inte ada.",case_coalesce_expression:"COALESCE(NULL,'x','y') returnerar 'x'.",alias_scope_error:"SELECT price*2 AS p ... WHERE p>10 är ogiltig i PracticeSQL-1.",write_single_table_filter:"SELECT name FROM users WHERE active=TRUE.",
      null_comparison:"NULL=NULL är UNKNOWN.",three_valued_boolean:"FALSE AND UNKNOWN är FALSE.",where_unknown_filter:"En NULL-ålder överlever inte WHERE age>=18.",is_null_predicate:"email IS NULL väljer endast NULL-markören.",null_arithmetic_case:"5+NULL är NULL; CASE WHEN UNKNOWN väljer ELSE.",null_in_not_in:"3 NOT IN (1,2,NULL) är UNKNOWN.",unknown_contexts:"CHECK(age>=0) godtar NULL om NOT NULL inte anges separat.",repair_null_bug:"Ersätt email=NULL med email IS NULL.",
      projection_multiplicity:"A,A,B projicerat som city förblir A,A,B.",distinct_result:"DISTINCT på NULL,NULL,1 ger NULL,1.",order_by_single_multi:"ORDER BY letter ASC,n DESC sorterar n fallande endast inom varje bokstav.",null_ordering_explicit:"ASC NULLS LAST ger 1,2,NULL.",sort_tie_determinism:"ORDER BY age är ofullständig om två namn har samma ålder.",limit_offset:"ORDER BY id LIMIT 2 OFFSET 2 ger position 3 och 4.",
      cross_join_result:"Två rader korsade med tre rader ger sex.",inner_join_result:"Två rader med key=1 joinade med tre sådana rader ger sex.",join_null_keys:"Två NULL-nycklar matchar inte under ON a.k=b.k.",left_join_result:"En vänsterrad med två träffar ger två rader och ingen tredje utfylld rad.",on_vs_where_outer_join:"Ett högersidesfilter i WHERE kan ta bort utfyllda vänsterrader.",self_join:"employee.manager_id=m.id joinar en anställd med dess chefsalias.",many_to_many_join:"Tre enrollment-rader för en student ger tre kursrader.",join_cardinality_bounds:"Frekvenserna 2 och 3 för en nyckel bidrar med sex rader.",write_join_query:"Alla kunder, även utan beställningar, kräver customers LEFT JOIN orders.",
      aggregate_single_group:"Över noll rader är COUNT(*) 0 medan SUM(x) är NULL.",count_star_expression_distinct:"För 1,NULL,1 är antalen 3,2,1.",group_by_result:"Två NULL-gruppnycklar bildar en grupp.",where_before_group:"En grupp utan överlevande rader får ingen utdatarad.",having_group_filter:"HAVING COUNT(*)>=2 behåller grupper med minst två rader.",grouping_validity:"SELECT dept,name,COUNT(*) GROUP BY dept är ogiltig.",outer_join_zero_count:"COUNT(child.id) ger noll för en förälder utan barn.",write_aggregate_query:"Använd HAVING COUNT(*)>=3 för att filtrera grupper efter antal beställningar.",
      scalar_subquery:"5=(SELECT x FROM empty) är UNKNOWN.",exists_subquery:"EXISTS(SELECT NULL FROM one_row) är TRUE.",correlated_exists:"Varje kund testar om en matchande orderrad finns.",in_subquery:"Ett NULL i ett resultat utan träff gör IN till UNKNOWN.",any_all_quantifier:"5>ALL(tom mängd) är TRUE.",union_all_union:"{1,2} UNION ALL {2,3} innehåller två rader med 2.",intersect_except:"{NULL,1} EXCEPT {NULL} ger {1}.",set_operation_validity:"Två kolumner UNION en kolumn är ogiltigt.",
      insert_defaults_constraints:"Utelämnat active DEFAULT TRUE lagrar TRUE.",update_result:"SET a=b,b=a byter plats på de gamla värdena.",delete_result:"RESTRICT avvisar borttagning av en förälder som har barn.",check_not_null_unique:"CHECK(age>=0) ensamt godtar NULL-ålder.",foreign_key_action:"ON UPDATE CASCADE ändrar matchande barnnycklar.",statement_atomicity:"En tvåradersinsättning med en duplicerad primärnyckel sätter inte in någon rad.",transaction_commit_rollback:"Uppdatera 5→7 och sedan ROLLBACK lämnar det bekräftade värdet 5.",isolation_schedule:"En snapshot-transaktion upprepar sin ursprungliga läsning efter att en annan transaktion bekräftar.",
      functional_dependency_check:"(A,1),(A,2) bryter mot X→Y.",attribute_closure:"A→B,B→C ger A+={A,B,C}.",anomaly_identification:"Ett avdelningstelefonnummer som upprepas per anställd ger en uppdateringsanomali.",normal_form_classify:"Nyckeln AB med A→C där C inte är primt bryter mot 2NF.",decompose_schema:"dept→phone ger Dept(dept,phone) plus Employee(emp,dept).",lossless_join_check:"Gemensamt B med B→C gör AB och BC förlustfria.",schema_relationship_design:"Enrollment bär student_id, course_id och enrollment_date.",
      btree_prefix_usability:"Index (a,b) stöder a=3 AND b>5 men inte b=5 ensamt som prefixsökning.",index_lookup_trace:"Nycklarna 1,3,3,8 med key=3 undersöker två poster.",covering_index:"Index (email,id) täcker SELECT id WHERE email=... .",selectivity_plan_choice:"Indexkostnad 4 plus två uppslag slår skanningskostnad 100.",index_write_tradeoff:"För en visad arbetslast kan (a,b) göra ett separat (a) överflödigt, men inte (b).",plan_semantics_distinction:"En indexskanning garanterar inte utdataordning utan ORDER BY."
    },
    generated:{
      modelNote:"PracticeSQL-1; NULL är en särskild markör och oordnade resultat är påsar om frågan inte säger annat.",
      prompts:{lookup:"Läs schemat och välj det exakta svaret.",classify:"Klassificera det visade relationsobjektet.",valid:"Är den visade operationen giltig?",operation:"Vilken operation eller fas visas?",schema:"Välj schemat som uppfyller kravet.",result:"Välj det exakta resultatet.",rows:"Vilka radidentifierare returneras?",truth:"Beräkna uttrycket med SQL:s trevärda logik.",match:"Vilka visade värden matchar?",scope:"Är denna namnanvändning giltig i PracticeSQL-1?",query:"Välj frågan som exakt genomför kravet.",guarantee:"Vilket påstående är garanterat?",order:"Välj det exakta ordnade resultatet.",count:"Hur många resultatrader skapas?",compare:"Jämför de två visade operationerna.",aggregate:"Beräkna det begärda aggregatresultatet.",context:"Vad gör UNKNOWN i den här kontexten?",state:"Välj det exakta sluttillståndet.",dependency:"Resonera från de visade funktionella beroendena.",index:"Välj den exakta slutsatsen om index eller plan."},
      labels:{schema:"Schema",table:"Tabell",rows:"Rader",query:"Fråga",requirement:"Krav",dependencies:"Funktionella beroenden",index:"Index",workload:"Arbetslast",schedule:"Schema",constraints:"Villkor",ordered:"ordnad",unorderedBag:"oordnad påse",rowIds:"rad-id",existing:"befintlig",proposed:"föreslagen"},
      choices:{yes:"Ja",no:"Nej",true:"TRUE",false:"FALSE",unknown:"UNKNOWN",null:"NULL",valid:"Giltig",invalid:"Fel",allowed:"Tillåten",rejected:"Avvisad",selection:"urval / radfiltrering",projection:"projektion / urvalslista",join:"join / parbildning",grouping:"gruppering / aggregering",dedup:"dubblettborttagning",candidate:"kandidatnyckel",superkey:"icke-minimal supernyckel",notkey:"inte en supernyckel",manyone:"många-till-en; valfri endast om nullbar",onetoone:"högst ett-till-ett",unordered:"Oordnad påse; dubbletter kan spela roll",orderedOnly:"Ordnad endast med ORDER BY",scan:"full tabellskanning",indexPlan:"indexuppslag",covered:"täcks av indexet",notCovered:"kräver tabelluppslag",lossless:"förlustfri",lossy:"förlustbringande",update:"uppdateringsanomali",insert:"insättningsanomali",delete:"borttagningsanomali",oneNF:"1NF",twoNF:"2NF",threeNF:"3NF",bcnf:"BCNF",commit:"bekräftas",abort:"avbryts"},
      explanationLead:"Tillämpa den visade regeln i PracticeSQL-1. Det exakta svaret är",nullToken:"SQL-null"
    },
    generatedReplacements:[
      ["many-to-one; child relationship is optional","många-till-en; barnrelationen är valfri"],["Row/match/group is not retained","Raden, träffen eller gruppen behålls inte"],["Constraint passes","Villkoret godkänns"],["CASE takes ELSE","CASE väljer ELSE"],
      ["A department phone is repeated in every employee row; changing it requires many edits.","Ett avdelningstelefonnummer upprepas i varje anställdrad; en ändring kräver många redigeringar."],["A department cannot be stored until its first employee exists.","En avdelning kan inte lagras innan dess första anställda finns."],["Deleting the final employee also removes the only stored department phone.","Att ta bort den sista anställda tar också bort det enda lagrade avdelningstelefonnumret."],
      ["Correct full and index scans return the same result bag.","Korrekta full- och indexskanningar ger samma resultatpåse."],["The index scan does not guarantee output order without ORDER BY.","Indexskanningen garanterar inte utdataordning utan ORDER BY."],["Moving a right predicate across LEFT JOIN phases requires semantic proof.","Att flytta ett högersidespredikat mellan faser i LEFT JOIN kräver ett semantiskt bevis."],["Plan cost changes method, not logical rows.","Plankostnaden ändrar metoden, inte de logiska raderna."],["An index scan always returns sorted SQL output.","En indexskanning returnerar alltid sorterad SQL-utdata."],["A cheaper plan may return fewer rows.","En billigare plan får returnera färre rader."],["Every predicate may move across LEFT JOIN unchanged.","Varje predikat kan flyttas oförändrat över LEFT JOIN."],
      ["one customer has many orders","en kund har många beställningar"],["students and courses are many-to-many; enrollment has a date","studenter och kurser är många-till-många; registreringen har ett datum"],["a user has at most one optional profile","en användare har högst en valfri profil"],
      ["order id and its customer name","beställnings-id och dess kundnamn"],["every customer and any order, including customers without orders","varje kund och eventuell beställning, även kunder utan beställningar"],["student and course names for enrollments","student- och kursnamn för registreringar"],
      ["total order amount per customer","totalt beställningsbelopp per kund"],["customers represented by at least three orders","kunder som representeras av minst tre beställningar"],["all customers and their active-order count, including zero","alla kunder och deras antal aktiva beställningar, inklusive noll"],["ids with score from 60 through 80, inclusive","id med score från och med 60 till och med 80"],
      ["statement rejected","satsen avvisas"],["cardinality error","kardinalitetsfel"],["first change remains","första ändringen kvarstår"],["all changes remain","alla ändringar kvarstår"],["partial cascade","partiell kaskad"],["unchanged","oförändrat"],["child relationship is optional","barnrelationen är valfri"],["requires a table lookup","kräver tabelluppslag"],["covered by the index","täcks av indexet"],["full table scan","full tabellskanning"],["index lookup","indexuppslag"],["T1 aborts","T1 avbryts"],["T2 aborts","T2 avbryts"],["T1 commits","T1 bekräftas"]
    ],
    generatedCodeReplacements:[
      ["requested: type of column name","begärt: typ för kolumnen name"],["claim: email is declared NOT NULL","påstående: email är deklarerad NOT NULL"],["claim: full row order is determined","påstående: hela radordningen är bestämd"],["claim: an ordered prefix search is usable","påstående: en ordnad prefixsökning kan användas"],["requested: number of examined index entries","begärt: antal undersökta indexposter"],[" -- old row"," -- gammal rad"],["key A, only A→BC","nyckel A, endast A→BC"],["index (a,b); entries","index (a,b); poster"],["keep INDEX(a,b); omit INDEX(a)","behåll INDEX(a,b); utelämna INDEX(a)"],["-- plan: index scan","-- plan: indexskanning"],["Left has one row","Left har en rad"],["L has one row","L har en rad"],["Right has ","Right har "],["A has ","A har "],["B has ","B har "],[" has one row with "," har en rad med "],[" has "," har "],[" rows with "," rader med "],["rows: ","rader: "],["row id=","rad-id="],[", column name",", kolumn name"],[" rows"," rader"],[" row(s)"," rad(er)"],[" row"," rad"],[" with active"," med active"],["matching ","matchande "],["no matching ","ingen matchande "],["one matching ","en matchande "],["other student(s) share at least one course","andra studenter delar minst en kurs"],["student s1 has ","student s1 har "],[" enrollment rows"," registreringsrader"],["key frequencies","nyckelfrekvenser"],["group counts","gruppantal"],["parent has no child","föräldern har inga barn"],["parent has two children","föräldern har två barn"],["parent has one inactive child","föräldern har ett inaktivt barn"],["existing id","befintligt id"],["existing email","befintlig email"],["existing PK","befintlig PK"],["existing NULL","befintligt NULL"],["existing 'A'","befintligt 'A'"],["one parent, one child","en förälder, ett barn"],["parent ids","föräldra-id"],["nullable FK","nullbar FK"],["committed x","bekräftat x"],["read committed x","läs bekräftat x"],["read x inside transaction","läs x i transaktionen"],["T1 reads x","T1 läser x"],["T2 writes ","T2 skriver "],[" and commits"," och bekräftar"],["T1 writes x and tries to commit","T1 skriver x och försöker bekräfta"],["T1 reads x again","T1 läser x igen"],["both INTEGER","båda INTEGER"],["INTEGER vs TEXT","INTEGER mot TEXT"],["no dependency from B","inget beroende från B"],["full scan cost","kostnad för full skanning"],["index cost","indexkostnad"],[" matches"," träffar"],["email equality reads save","likhetsläsningar på email sparar"],["writes cost","skrivningar kostar"],["flag reads save","flaggläsningar sparar"],["workload filters by","arbetslasten filtrerar på"],["never by b alone","aldrig enbart på b"],["query plus two candidate physical plans","fråga plus två fysiska kandidatplaner"],["cost =","kostnad ="],["context =","kontext ="]
    ],
    generatedWordReplacements:{
      "rows":"rader","row":"rad","has":"har","with":"med","matching":"matchande","match":"träff","existing":"befintlig","proposed":"föreslagen","one":"en","two":"två","three":"tre","other":"annan","student":"student","students":"studenter","course":"kurs","courses":"kurser","customer":"kund","customers":"kunder","order":"beställning","orders":"beställningar","parent":"förälder","parents":"föräldrar","child":"barn","children":"barn","active":"aktiv","inactive":"inaktiv","final":"slutlig","value":"värde","values":"värden","group":"grupp","groups":"grupper","count":"antal","cost":"kostnad","matches":"träffar","reads":"läsningar","writes":"skrivningar","save":"sparar","each":"vardera","same":"samma","result":"resultat","bag":"påse","without":"utan","including":"inklusive","including zero":"inklusive noll","no":"inga","all":"alla","empty":"tom","nullable":"nullbar","both":"båda","integer":"heltal","vs":"mot","committed":"bekräftat","read":"läs","writes":"skriver","commits":"bekräftar","tries":"försöker","again":"igen","inside":"inuti","transaction":"transaktionen","statement":"sats","rejected":"avvisad","allowed":"tillåten","begin":"början","end":"slut","greater":"större","less":"mindre","names":"namn","name":"namn","including":"inklusive","requirement":"krav","workload":"arbetslast","filters":"filtrerar","never":"aldrig","alone":"ensamt","prefix":"prefix","search":"sökning"
    }
  }
};
