const titles = {
  symbolize_proposition:"Symbolize a proposition", verbalize_formula:"Read a symbolic formula", identify_main_connective:"Identify the main connective", scope_parenthesization:"Resolve scope and parentheses", conditional_direction:"Necessary and sufficient conditions",
  evaluate_formula_assignment:"Evaluate under an assignment", connective_missing_value:"Recover a missing truth value", truth_table_column:"Complete a truth-table column", classify_formula:"Classify a formula", satisfying_assignment:"Find a satisfying assignment", premise_set_consistency:"Test premise consistency",
  negate_formula:"Negate a formula", conditional_forms:"Converse, inverse, and contrapositive", equivalent_rewrite:"Apply an equivalence law", equivalence_decision:"Decide logical equivalence", equivalence_counterassignment:"Find an equivalence counterexample", normal_form_conversion:"Convert to normal form",
  infer_rule_conclusion:"Infer a one-step conclusion", identify_inference_rule:"Identify an inference rule", complete_argument:"Complete an argument form", argument_validity:"Test argument validity", argument_countermodel:"Find an argument countermodel", valid_form_or_fallacy:"Distinguish rules and fallacies", symbolized_natural_argument:"Analyze a controlled-language argument",
  justify_proof_line:"Justify a proof line", choose_next_proof_step:"Choose the next proof step", fill_proof_gap:"Fill a proof gap", order_proof_steps:"Order proof steps", assumption_discharge:"Discharge an assumption",
  symbolize_quantified_sentence:"Symbolize a quantified sentence", negate_quantified_formula:"Negate quantified formulas", evaluate_unary_model:"Evaluate a unary finite model", evaluate_relation_model:"Evaluate a relation model", quantifier_order_contrast:"Contrast quantifier order", witness_or_counterexample:"Find a witness or counterexample", quantified_inference:"Apply quantified inference", categorical_argument_validity:"Test categorical validity"
};

const rules = {
  symbolize_proposition:"Build the semantic structure from the main connective outward; ‘P only if Q’ is P→Q.", verbalize_formula:"Split the AST at its widest-scope connective and preserve inclusive ‘or’ and conditional direction.", identify_main_connective:"The main connective is the root of the formula tree, not necessarily the first symbol shown.", scope_parenthesization:"Use ¬, ∧, ∨, →, ↔ precedence in that order; implication associates to the right.", conditional_direction:"Rewrite the sentence as ‘If antecedent, then consequent’; the antecedent is sufficient and the consequent necessary.",
  evaluate_formula_assignment:"Evaluate inner formulas first. A→B is false only in the T→F row.", connective_missing_value:"Enumerate both possible values; if both fit, the missing value is not determined.", truth_table_column:"Use T-before-F row order and evaluate the same AST independently on every row.", classify_formula:"All T is a tautology, all F a contradiction, and a mixed column a contingency.", satisfying_assignment:"Any named assignment with the requested final truth value is valid.", premise_set_consistency:"A premise set is consistent exactly when one assignment makes every premise true together.",
  negate_formula:"Negate at the outer boundary, swapping ∧/∨ under De Morgan and using ¬(P→Q)≡P∧¬Q.", conditional_forms:"Converse swaps sides; inverse negates both; contrapositive swaps and negates both.", equivalent_rewrite:"A valid rewrite preserves the complete truth column and applies a named law at a real subtree.", equivalence_decision:"Equivalent formulas agree on every assignment, not merely on one convenient row.", equivalence_counterassignment:"A single assignment where the truth values differ proves non-equivalence.", normal_form_conversion:"Eliminate →/↔, push negations to atoms, then distribute; also verify the requested CNF or DNF shape.",
  infer_rule_conclusion:"Match whole subformulas to a rule schema before substituting its conclusion.", identify_inference_rule:"Abstract the concrete formulas to A and B, preserving their roles and polarity.", complete_argument:"The missing line must make the displayed lines an exact instance of the named schema.", argument_validity:"Validity means there is no row with all premises true and the conclusion false.", argument_countermodel:"A countermodel must satisfy every premise and falsify the conclusion.", valid_form_or_fallacy:"MP and MT are valid; affirming the consequent and denying the antecedent are invalid.", symbolized_natural_argument:"Symbolize first, then judge the resulting formal argument independently of real-world plausibility.",
  justify_proof_line:"A justification needs the right rule, earlier citations, matching formulas, and accessible scope.", choose_next_proof_step:"A next step must be legal now and contribute to a validated route to the goal.", fill_proof_gap:"Use both the cited earlier lines and the later dependency to constrain the missing formula.", order_proof_steps:"Every cited dependency must occur earlier, and closed-scope lines cannot escape their subproof.", assumption_discharge:"→I turns an A…B subproof into A→B; ¬I turns A…⊥ into ¬A.",
  symbolize_quantified_sentence:"Universal class restriction uses implication; existential class restriction uses conjunction.", negate_quantified_formula:"Every crossed negation swaps ∀ and ∃, then negates the matrix without capturing variables.", evaluate_unary_model:"Enumerate the explicit nonempty domain; an empty predicate class can make a universal conditional vacuously true.", evaluate_relation_model:"Treat R(a,b) as the ordered pair (a,b); enumerate bound-variable tuples exactly.", quantifier_order_contrast:"∀x∃y permits different y values; ∃y∀x requires one common y.", witness_or_counterexample:"Substitute each displayed element and accept every element that witnesses or refutes the claim.", quantified_inference:"Distinguish every object, some unspecified object, and one named object.", categorical_argument_validity:"Use modern first-order semantics: universal premises alone do not imply that a class exists."
};

const examples = {
  symbolize_proposition:"‘P only if Q’ → P→Q", verbalize_formula:"¬(P∧Q): it is not the case that both P and Q", identify_main_connective:"(P→Q)↔¬R has ↔ at its root", scope_parenthesization:"P→Q→R parses as P→(Q→R)", conditional_direction:"Q is required for P → P→Q",
  evaluate_formula_assignment:"F→F = T", connective_missing_value:"F→?=T: not determined", truth_table_column:"P∧Q: T,F,F,F", classify_formula:"P∨¬P is a tautology", satisfying_assignment:"P→Q is false at P=T,Q=F", premise_set_consistency:"P→Q, P, ¬Q is inconsistent",
  negate_formula:"¬(P∨Q) ≡ ¬P∧¬Q", conditional_forms:"contrapositive(P→Q)=¬Q→¬P", equivalent_rewrite:"P→Q ≡ ¬P∨Q", equivalence_decision:"P→Q ≡ ¬P∨Q", equivalence_counterassignment:"P→Q versus Q→P: P=T,Q=F", normal_form_conversion:"P→Q in CNF is ¬P∨Q",
  infer_rule_conclusion:"P→Q, P ∴ Q", identify_inference_rule:"P→Q, ¬Q ∴ ¬P: modus tollens", complete_argument:"P→Q, ?, ∴ Q: P", argument_validity:"P→Q, Q ∴ P has countermodel P=F,Q=T", argument_countermodel:"All premises T; conclusion F", valid_form_or_fallacy:"P→Q, Q ∴ P affirms the consequent", symbolized_natural_argument:"If L then W; L; therefore W",
  justify_proof_line:"P∧Q ⊢ P by ∧E", choose_next_proof_step:"P→Q, P: derive Q by →E", fill_proof_gap:"P→Q, P, [Q]", order_proof_steps:"derive Q before using Q→R", assumption_discharge:"assume P … derive Q; conclude P→Q",
  symbolize_quantified_sentence:"Every A is B: ∀x(A(x)→B(x))", negate_quantified_formula:"¬∀xP(x) ≡ ∃x¬P(x)", evaluate_unary_model:"A=∅ makes ∀x(A(x)→B(x)) true", evaluate_relation_model:"R={(a,b)} makes ∃x∃yR(x,y) true", quantifier_order_contrast:"each has someone ≠ one works for all", witness_or_counterexample:"P={a,c}: a and c are witnesses", quantified_inference:"∀x(C→M), C(a) ∴ M(a)", categorical_argument_validity:"Every A is B; every B is C ∴ every A is C"
};

export default {
  code:"en", lang:"en", suffix:"",
  text:{
    localeCode:"en", appTitle:"Logic Practice", brandSubtitle:"Practice symbols, truth conditions, equivalence, arguments, short proofs, quantifiers, and exact finite models.", educationalNote:"Pinned model: classical bivalent propositional and finite first-order logic · exact local enumeration · no backend or theorem-proving service.",
    summary:{aria:"Progress summary",mastery:"Avg mastery",accuracy:"Accuracy",attempts:"Attempts"}, nav:{aria:"Main",practice:"Practice",matrix:"Matrix",stats:"Stats",settings:"Settings",learn:"Learn"},
    practice:{modeAria:"Practice mode",adaptive:"Adaptive",manual:"Manual",pause:"Pause",paused:"Paused",learnThis:"Learn this",category:"Category",family:"Question family",level:"Level",mastery:"0% mastery",masterySuffix:"mastery",check:"Check",next:"Next",skip:"Skip",choose:"Choose…",keypadAria:"Logical-symbol answer keypad",delete:"Del",clear:"Clear",nextField:"Move to the next answer field",nextFieldShort:"Field →",pauseText:"The timer is stopped for this question.",resume:"Resume",controlsAria:"Practice controls",masteryMetric:"Mastery",accuracyMetric:"Accuracy",streak:"Streak",avgTime:"Avg time",space:"Space"},
    matrix:{title:"Logic Skill Matrix",intro:"Every cell opens one stable logic family at one structural difficulty level."}, stats:{title:"Stats",intro:"Progress is tracked independently for every family and level.",totalAttempts:"Total attempts",totalCorrect:"Total correct",totalTime:"Total time",practicedLevels:"Practiced levels",needsWork:"Needs Work",strongest:"Strongest",tries:"tries",noAttemptsYet:"No attempts yet"},
    settings:{title:"Settings",intro:"Stored locally in this browser.",adaptiveCategories:"Adaptive categories",data:"Data",dataIntro:"Export, import, or reset local progress.",progressJson:"Progress JSON",export:"Export",copy:"Copy",import:"Import",reset:"Reset"}, learn:{title:"Learn",intro:"The exact model, decisive rule, representative example, and common trap for every family."}, messages:{correct:"Correct",notQuite:"Not quite",expected:"Expected",time:"Time",invalidJson:"Invalid JSON",resetConfirm:"Reset all local progress?",parseError:"Use the displayed logical notation or supported keyboard aliases."},
    categories:{symbols:"Symbols & Scope",truth:"Truth Conditions",equivalence:"Equivalence",arguments:"Arguments & Rules",proofs:"Short Proofs",quantifiers:"Quantifiers & Models"}, families:Object.fromEntries(Object.keys(titles).map(id=>[id,{title:titles[id],rule:rules[id],example:examples[id]}])),
    generated:{assignment:"Assignment",premises:"Premises",conclusion:"Conclusion",domain:"Domain",predicates:"Predicates",relation:"Relation",formula:"Formula",goal:"Goal",proof:"Proof",modernSemantics:"Use modern first-order semantics; universal claims have no existential import.",question:"Choose or enter the exact answer.",truthValue:"What is the truth value?",symbolize:"Symbolize the controlled sentence.",verbalize:"Which controlled sentence has exactly this structure?",mainConnective:"Which occurrence is the main connective?",parenthesize:"Choose the parse required by the stated precedence.",conditionalRoles:"Which role assignment is correct?",missing:"What can be concluded about the missing truth value?",completeColumn:"Choose the final truth-table column in T-before-F row order.",classify:"Classify the formula.",satisfy:"Choose an assignment with the requested property.",consistent:"Are the premises jointly consistent?",negate:"Enter a formula equivalent to the negation.",conditionalForm:"Enter the requested conditional form.",rewrite:"Choose the equivalent rewrite.",equivalent:"Are the formulas logically equivalent?",counterassignment:"Choose a distinguishing assignment.",normalForm:"Enter the requested normal form.",infer:"What follows in one step?",identifyRule:"Which rule is instantiated?",completeArgument:"Choose the missing line.",validity:"Is the argument formally valid?",countermodel:"Choose a countermodel: every premise true, conclusion false.",classifyForm:"Classify the argument form.",naturalArgument:"Symbolize the controlled argument, then classify it.",justify:"Choose the exact justification.",nextStep:"Which option is a legal, goal-directed next step?",proofGap:"Which formula fills the proof gap?",proofOrder:"Which ordering respects every dependency?",discharge:"What follows outside the closed subproof?",quantify:"Choose the matching quantified formula.",quantifierNegation:"Choose the equivalent formula with negation on the matrix.",evaluateModel:"Is the formula true in this finite model?",compareOrder:"Evaluate both quantifier orders.",witness:"Choose a valid witness or counterexample.",quantifiedInference:"Which conclusion follows?",categorical:"Is the categorical argument valid?",worked:"Decisive reasoning:",trap:"Common trap:",legend:"Legend",andSentence:"P and Q",orSentence:"P or Q, or both",notSentence:"P is not the case",ifSentence:"If P, then Q",onlyIfSentence:"P only if Q",iffSentence:"P if and only if Q",neitherSentence:"Neither P nor Q",valid:"Valid",invalid:"Invalid",yes:"Yes",no:"No",true:"True",false:"False",tautology:"Tautology",contradiction:"Contradiction",contingency:"Contingency",determinedT:"Determined: T",determinedF:"Determined: F",notDetermined:"Not determined",consistentYes:"Consistent",consistentNo:"Inconsistent",noWitness:"None",sentenceEvery:"Every A is B.",sentenceSomeNot:"Some A is not B.",sentenceEveryRelSome:"Every A relates to some B."}
  }
};
